version: '3'
services:
  server:
    build:
      context: ./cyber-center-website-back
      dockerfile: Dockerfile
    container_name: cyber-center-server
    ports:
      - "15001:15001"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}a
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    hostname: server ø

  client:
    build:
      context: ./cyber-center-website-front
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_HOST: ${SERVER_HOST}
        REACT_APP_SERVER_PORT: ${SERVER_PORT}
    container_name: cyber-center-client
    ports:
      - "15000:15000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    hostname: client
    environment:
      REACT_APP_SERVER_PORT: "15000"
      REACT_APP_SERVER_HOST: "46.219.127.6"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
 
  db:
    image: postgres
    container_name: cyber-center-db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  ftp:
    build:
      context: ./cyber-center-website-ftp
      dockerfile: Dockerfile

    container_name: cyber-center-ftp
    ports:
      - "15005:15005"
    hostname: ftp
